version: '3.8'

# 🐳 Docker Compose Dev - Mestres do Café Development
# Ambiente de desenvolvimento com hot reload e estrutura organizada
# Inclui bind mounts para documentação e desenvolvimento ágil

services:
  # Aplicação principal em modo desenvolvimento
  mestres-cafe-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mestres-cafe-dev
    ports:
      - "5174:5174"  # Vite dev server
      - "3001:3001"  # Backend API
      - "5000:5000"  # Unified server
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001
      - PORT=5000
      - BACKEND_PORT=3001
      - FRONTEND_PORT=5174
      # Configurações para desenvolvimento
      - DOCS_PATH=/app/documentation
      - SCRIPTS_PATH=/app/scripts
      - PUBLIC_IMAGES_PATH=/app/public/images
      - HOT_RELOAD=true
    volumes:
      # Bind mounts para desenvolvimento ágil
      - ./src:/app/src
      - ./public:/app/public
      - ./server:/app/server
      - ./database:/app/database
      - ./scripts:/app/scripts
      - ./documentation:/app/documentation
      - ./package.json:/app/package.json
      - ./vite.config.js:/app/vite.config.js
      - ./tailwind.config.js:/app/tailwind.config.js
      # Persistir node_modules para performance
      - node_modules_cache:/app/node_modules
      # Dados temporários de desenvolvimento
      - dev_data:/app/server/data
      - dev_logs:/app/logs
    restart: unless-stopped
    networks:
      - dev-network
    depends_on:
      - postgres-dev
      - redis-dev
    command: >
      sh -c "
        npm install &&
        npm run dev:concurrent
      "

  # PostgreSQL para desenvolvimento
  postgres-dev:
    image: postgres:15-alpine
    container_name: mestres-cafe-db-dev
    environment:
      - POSTGRES_DB=mestres_cafe_dev
      - POSTGRES_USER=mestres_dev
      - POSTGRES_PASSWORD=dev123
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      # Scripts de desenvolvimento organizados
      - ./database/supabase-setup-completo.sql:/docker-entrypoint-initdb.d/01-setup.sql:ro
      - ./database/blog-functions.sql:/docker-entrypoint-initdb.d/02-blog.sql:ro
      - ./database/fix-products-table.sql:/docker-entrypoint-initdb.d/03-fixes.sql:ro
    ports:
      - "5433:5432"  # Porta diferente para não conflitar
    restart: unless-stopped
    networks:
      - dev-network

  # Redis para desenvolvimento
  redis-dev:
    image: redis:7-alpine
    container_name: mestres-cafe-redis-dev
    command: redis-server --appendonly yes
    ports:
      - "6380:6379"  # Porta diferente para desenvolvimento
    volumes:
      - redis_dev_data:/data
    restart: unless-stopped
    networks:
      - dev-network

  # Adminer para gestão do banco em desenvolvimento
  adminer:
    image: adminer:latest
    container_name: mestres-cafe-adminer
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres-dev
      - ADMINER_DESIGN=nette
    depends_on:
      - postgres-dev
    restart: unless-stopped
    networks:
      - dev-network
    profiles:
      - tools

  # RedisInsight para visualização do Redis
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: mestres-cafe-redis-insight
    ports:
      - "8001:8001"
    volumes:
      - redis_insight_data:/db
    depends_on:
      - redis-dev
    restart: unless-stopped
    networks:
      - dev-network
    profiles:
      - tools

  # Mailhog para teste de emails em desenvolvimento
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mestres-cafe-mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    restart: unless-stopped
    networks:
      - dev-network
    profiles:
      - tools

volumes:
  # Volumes de desenvolvimento
  postgres_dev_data:
    driver: local
  
  redis_dev_data:
    driver: local
  
  redis_insight_data:
    driver: local
  
  node_modules_cache:
    driver: local
  
  dev_data:
    driver: local
  
  dev_logs:
    driver: local

networks:
  dev-network:
    driver: bridge
    name: mestres-cafe-dev-network
    ipam:
      config:
        - subnet: 172.21.0.0/16 